inherit_from: .rubocop_todo.yml
Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 55

Metrics/MethodLength:
  Max: 15

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# Line is too long を無視
Metrics/LineLength:
  Enabled: false

# Use nested module/class definitions instead of compact style. を無視
Style/ClassAndModuleChildren:
  Enabled: false
