version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: with_exo_development
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"

  test-db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: with_exo_test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test
    ports:
      - '3307:3306' 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - test-db
    ports:
      - "3000:3000"
    volumes:
      - .:/app